# Generated by Django 4.0.3 on 2023-08-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='img',
            new_name='image',
        ),
    ]
