# Generated by Django 4.0.3 on 2023-08-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_allfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllFood',
        ),
    ]
