# Generated by Django 4.0.3 on 2023-08-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_chefsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('sectionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.sectionmodel')),
                ('gallery_image', models.ImageField(upload_to='GalleryImage')),
            ],
            bases=('app.sectionmodel',),
        ),
    ]
