# Generated by Django 4.0.3 on 2023-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=20)),
                ('time', models.TimeField(max_length=20)),
                ('people', models.IntegerField()),
                ('msg', models.TextField()),
            ],
        ),
    ]
