# Generated by Django 4.0.3 on 2023-08-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='desc',
            field=models.TextField(max_length=250),
        ),
    ]
