# Generated by Django 4.0.3 on 2023-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sectionmodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='desc',
            field=models.TextField(),
        ),
    ]
