# Generated by Django 4.0.3 on 2023-08-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sectionmodel_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('sectionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.sectionmodel')),
                ('price', models.FloatField()),
                ('events_image', models.ImageField(upload_to='EventsImage')),
            ],
            bases=('app.sectionmodel',),
        ),
    ]
