# Generated by Django 4.0.3 on 2023-08-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('uttara_sec-1', 'uttara_sec-1'), ('Mirpur-2', 'Mirpur-2'), ('Muradpur', 'Muradpur'), ('Feni', 'Feni')], max_length=50),
        ),
    ]
